#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
	local enabled
	enabled="$(uci -q get traffic_statistic.main.enabled)"
	[ "${enabled:-1}" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/traffic-statisticd
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param limits nofile="256 256"
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger traffic_statistic network
}

reload_service() {
	stop
	start
}
